(setq a 3)
(setq b 1)
(setq c 2)
(setq lo b)
(if (< a lo)
    (setq lo a)
    (setq lo lo))
(if (< c lo)
    (setq lo c)
    (setq lo lo))
(setq hi a)
(if (> b hi)
    (setq hi b)
    (setq hi hi))
(if (> c hi)
    (setq hi c)
    (setq hi hi))
(setq mid (- (+ a (+ b c)) (+ lo hi)))
(print lo)
(print mid)
(print hi)
